### ISSUE TITLE
Link to pdf version not working

### ISSUE THREAD

**Issue by lubojr** [GISMentors/postgis-zacatecnik#1]
http://training.gismentors.eu/postgis-zacatecnik/
"Text školení je dostupný i v tisknutelné formě PDF." 
http://training.gismentors.eu/postgis-zacatecnik/skoleni-postgis-zacatecnik.pdf
Link returns error 404

**Comment by jachym** [comment]
We are working on this - it's the issue between two sphinx versions, sry, you have to live with the HTML version for a while.
